# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from resolveagent.v1 import agent_pb2 as resolveagent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resolveagent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService manages agent lifecycle and execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/resolveagent.v1.AgentService/CreateAgent',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/resolveagent.v1.AgentService/GetAgent',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/resolveagent.v1.AgentService/ListAgents',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.UpdateAgent = channel.unary_unary(
                '/resolveagent.v1.AgentService/UpdateAgent',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/resolveagent.v1.AgentService/DeleteAgent',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.ExecuteAgent = channel.unary_stream(
                '/resolveagent.v1.AgentService/ExecuteAgent',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentResponse.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/resolveagent.v1.AgentService/GetExecution',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.GetExecutionRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.Execution.FromString,
                _registered_method=True)
        self.ListExecutions = channel.unary_unary(
                '/resolveagent.v1.AgentService/ListExecutions',
                request_serializer=resolveagent_dot_v1_dot_agent__pb2.ListExecutionsRequest.SerializeToString,
                response_deserializer=resolveagent_dot_v1_dot_agent__pb2.ListExecutionsResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService manages agent lifecycle and execution.
    """

    def CreateAgent(self, request, context):
        """CreateAgent creates a new agent definition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """GetAgent retrieves an agent by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """ListAgents lists agents with filtering and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """UpdateAgent updates an existing agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """DeleteAgent removes an agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgent(self, request, context):
        """ExecuteAgent runs an agent and streams results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """GetExecution retrieves execution details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExecutions(self, request, context):
        """ListExecutions lists executions for an agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.CreateAgentRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.GetAgentRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.ListAgentsRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.ListAgentsResponse.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.UpdateAgentRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.DeleteAgentRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'ExecuteAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentResponse.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.GetExecutionRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.Execution.SerializeToString,
            ),
            'ListExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutions,
                    request_deserializer=resolveagent_dot_v1_dot_agent__pb2.ListExecutionsRequest.FromString,
                    response_serializer=resolveagent_dot_v1_dot_agent__pb2.ListExecutionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resolveagent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resolveagent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService manages agent lifecycle and execution.
    """

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/CreateAgent',
            resolveagent_dot_v1_dot_agent__pb2.CreateAgentRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/GetAgent',
            resolveagent_dot_v1_dot_agent__pb2.GetAgentRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/ListAgents',
            resolveagent_dot_v1_dot_agent__pb2.ListAgentsRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/UpdateAgent',
            resolveagent_dot_v1_dot_agent__pb2.UpdateAgentRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/DeleteAgent',
            resolveagent_dot_v1_dot_agent__pb2.DeleteAgentRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/resolveagent.v1.AgentService/ExecuteAgent',
            resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.ExecuteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/GetExecution',
            resolveagent_dot_v1_dot_agent__pb2.GetExecutionRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resolveagent.v1.AgentService/ListExecutions',
            resolveagent_dot_v1_dot_agent__pb2.ListExecutionsRequest.SerializeToString,
            resolveagent_dot_v1_dot_agent__pb2.ListExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
