# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resolveagent/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resolveagent/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cresolveagent/v1/common.proto\x12\x0fresolveagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n\x11PaginationRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"B\n\x12PaginationResponse\x12\x17\n\x0fnext_page_token\x18\x01 \x01(\t\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\x9b\x01\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x08metadata\x18\x03 \x03(\x0b\x32*.resolveagent.v1.ErrorDetail.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa5\x03\n\x0cResourceMeta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x39\n\x06labels\x18\x04 \x03(\x0b\x32).resolveagent.v1.ResourceMeta.LabelsEntry\x12\x43\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32..resolveagent.v1.ResourceMeta.AnnotationsEntry\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x08 \x01(\t\x12\x0f\n\x07version\x18\t \x01(\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xa4\x01\n\x0eResourceStatus\x12\x1f\n\x1bRESOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16RESOURCE_STATUS_ACTIVE\x10\x01\x12\x1c\n\x18RESOURCE_STATUS_INACTIVE\x10\x02\x12\x19\n\x15RESOURCE_STATUS_ERROR\x10\x03\x12\x1c\n\x18RESOURCE_STATUS_DELETING\x10\x04\x42PZNgithub.com/ai-guru-global/resolve-agent/pkg/api/resolveagent/v1;resolveagentv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resolveagent.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/ai-guru-global/resolve-agent/pkg/api/resolveagent/v1;resolveagentv1'
  _globals['_ERRORDETAIL_METADATAENTRY']._loaded_options = None
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RESOURCEMETA_LABELSENTRY']._loaded_options = None
  _globals['_RESOURCEMETA_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_RESOURCEMETA_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_RESOURCEMETA_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_RESOURCESTATUS']._serialized_start=793
  _globals['_RESOURCESTATUS']._serialized_end=957
  _globals['_PAGINATIONREQUEST']._serialized_start=82
  _globals['_PAGINATIONREQUEST']._serialized_end=140
  _globals['_PAGINATIONRESPONSE']._serialized_start=142
  _globals['_PAGINATIONRESPONSE']._serialized_end=208
  _globals['_ERRORDETAIL']._serialized_start=211
  _globals['_ERRORDETAIL']._serialized_end=366
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_start=319
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_end=366
  _globals['_RESOURCEMETA']._serialized_start=369
  _globals['_RESOURCEMETA']._serialized_end=790
  _globals['_RESOURCEMETA_LABELSENTRY']._serialized_start=693
  _globals['_RESOURCEMETA_LABELSENTRY']._serialized_end=738
  _globals['_RESOURCEMETA_ANNOTATIONSENTRY']._serialized_start=740
  _globals['_RESOURCEMETA_ANNOTATIONSENTRY']._serialized_end=790
# @@protoc_insertion_point(module_scope)
