# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resolveagent/v1/selector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resolveagent/v1/selector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from resolveagent.v1 import agent_pb2 as resolveagent_dot_v1_dot_agent__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresolveagent/v1/selector.proto\x12\x0fresolveagent.v1\x1a\x1bresolveagent/v1/agent.proto\x1a\x1cgoogle/protobuf/struct.proto\"i\n\x15\x43lassifyIntentRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12(\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"~\n\x16\x43lassifyIntentResponse\x12\x13\n\x0bintent_type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x65ntities\x18\x03 \x03(\t\x12)\n\x08metadata\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"n\n\x0cRouteRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x13\n\x0bintent_type\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12(\n\x07\x63ontext\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"T\n\rRouteResponse\x12\x30\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0b\x32\x1e.resolveagent.v1.RouteDecision\x12\x11\n\treasoning\x18\x02 \x01(\t2\xbc\x01\n\x0fSelectorService\x12\x61\n\x0e\x43lassifyIntent\x12&.resolveagent.v1.ClassifyIntentRequest\x1a\'.resolveagent.v1.ClassifyIntentResponse\x12\x46\n\x05Route\x12\x1d.resolveagent.v1.RouteRequest\x1a\x1e.resolveagent.v1.RouteResponseBPZNgithub.com/ai-guru-global/resolve-agent/pkg/api/resolveagent/v1;resolveagentv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resolveagent.v1.selector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/ai-guru-global/resolve-agent/pkg/api/resolveagent/v1;resolveagentv1'
  _globals['_CLASSIFYINTENTREQUEST']._serialized_start=110
  _globals['_CLASSIFYINTENTREQUEST']._serialized_end=215
  _globals['_CLASSIFYINTENTRESPONSE']._serialized_start=217
  _globals['_CLASSIFYINTENTRESPONSE']._serialized_end=343
  _globals['_ROUTEREQUEST']._serialized_start=345
  _globals['_ROUTEREQUEST']._serialized_end=455
  _globals['_ROUTERESPONSE']._serialized_start=457
  _globals['_ROUTERESPONSE']._serialized_end=541
  _globals['_SELECTORSERVICE']._serialized_start=544
  _globals['_SELECTORSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
