apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resolveagent.name" . }}
  labels:
    {{- include "resolveagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.postgresql.auth.password | quote }}
  redis-password: {{ .Values.redis.password | quote }}
