apiVersion: v1
kind: Service
metadata:
  name: {{ include "resolvenet.name" . }}-runtime
  labels:
    {{- include "resolvenet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.runtime.service.port }}
      targetPort: grpc
      name: grpc
  selector:
    {{- include "resolvenet.runtime.selectorLabels" . | nindent 4 }}
